# example Kubernetes deployment manifest
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tijana-app
  labels:
    app: tijana-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tijana-app
  template:
    metadata:
      labels:
        app: tijana-app
    spec:
      containers:
        - name: tijana-app
          image: tijanao/projecttijana:latest
          ports:
            - containerPort: 4000
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 20
